"""E2E test client for CloudConvert via x402gate.

This client simulates a file conversion flow:
1. Creates a small test text file.
2. Sends it as multipart/form-data to the gateway → gets 402.
3. Signs payment and retries with PAYMENT-SIGNATURE header.
4. Downloads the converted result.

Usage:
    python tests/e2e/x402_cloudconvert_client.py
"""

import asyncio
import base64
import logging
import os
import sys

import httpx
from eth_account import Account
from helpers import save_from_urls
from x402 import PaymentRequired, x402Client
from x402.mechanisms.evm.exact import ExactEvmScheme
from x402.mechanisms.evm.signers import EthAccountSigner

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("x402-cloudconvert-client")


# A small HTML file for conversion to PDF (fast, uses minimal credits)
TEST_FILE_CONTENT = b"""<!DOCTYPE html>
<html>
<head><title>x402gate E2E Test</title></head>
<body>
<h1>CloudConvert E2E Test</h1>
<p>This file was generated by x402gate E2E test suite.</p>
<p>Timestamp: TEST_RUN</p>
</body>
</html>"""

TEST_FILE_NAME = "test_e2e.html"
OUTPUT_FORMAT = "pdf"


async def run_client():
    """Run the E2E client test."""
    gateway_url = os.environ.get("GATEWAY_URL", "http://localhost:4021")
    private_key = os.environ.get("BASE_E2ETEST_PRIVATE_KEY")

    if not private_key:
        logger.error("BASE_E2ETEST_PRIVATE_KEY env var not set")
        sys.exit(1)

    # Initialize x402 client with EVM signer
    account = Account.from_key(private_key)
    signer = EthAccountSigner(account)
    x402_client = x402Client()
    x402_client.register("eip155:8453", ExactEvmScheme(signer))
    x402_client.register("eip155:84532", ExactEvmScheme(signer))

    logger.info("Client Address: %s", account.address)
    logger.info("Gateway URL: %s", gateway_url)
    logger.info("Converting %s → %s", TEST_FILE_NAME, OUTPUT_FORMAT)

    url = f"{gateway_url}/v1/cloudconvert/convert"

    async with httpx.AsyncClient() as http_client:
        # 1. Request without payment (multipart)
        logger.info("Sending initial request (no payment)...")
        response = await http_client.post(
            url,
            files={"file": (TEST_FILE_NAME, TEST_FILE_CONTENT)},
            data={"output_format": OUTPUT_FORMAT, "input_format": "html"},
        )

        if response.status_code != 402:
            logger.error("Expected 402, got %d: %s", response.status_code, response.text)
            sys.exit(1)

        logger.info("Got 402 Payment Required")

        # Parse the 402 response
        payment_required = PaymentRequired.model_validate(response.json())

        # 2. Sign payment
        logger.info("Signing payment...")
        try:
            payment_payload = await x402_client.create_payment_payload(payment_required)
            signature = base64.b64encode(
                payment_payload.model_dump_json(by_alias=True).encode()
            ).decode()
        except Exception as e:
            logger.error("Failed to sign payment: %s", e)
            sys.exit(1)

        # 3. Retry with payment (multipart + signature header)
        logger.info("Retrying with payment signature...")
        response = await http_client.post(
            url,
            files={"file": (TEST_FILE_NAME, TEST_FILE_CONTENT)},
            data={"output_format": OUTPUT_FORMAT, "input_format": "html"},
            headers={"PAYMENT-SIGNATURE": signature},
            timeout=120.0,
        )

        if response.status_code == 200:
            result = response.json()
            logger.info("Success! Result: %s", result)

            # Download converted file
            data = result.get("data", result)
            result_url = data.get("url")
            filename = data.get("filename", "output")
            if result_url:
                await save_from_urls([result_url], f"cloudconvert_{filename}", http_client)
        else:
            logger.error("Failed: %d %s", response.status_code, response.text)
            sys.exit(1)


if __name__ == "__main__":
    asyncio.run(run_client())
